// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
//   };


  

import React from 'react'
import Banner from '@/common/Banner'
import Aboutme from '@/components/Aboutme'
import Footer from '@/components/Footer'
import Stacks from '@/components/Stacks'

const page = () => {
  return (
    <div>
      <Banner title={"About"}/>
      <Aboutme/>
      <Stacks/>

    </div>
  )
}

export default page
